taxes:
  GST:
    versions:
      - starts: 2011-01-01
        ends: 2011-12-31
        percentage: 5

states:
  qc:
    rules:
      same_state: [GST, QST]
      same_country: GST
    taxes:
      QST:
        apply_on: GST
        versions:
          - starts: 2011-01-01
            ends: 2011-12-31
            percentage: 8.5
        
          - starts: 2012-01-01
            ends: 2012-12-31
            percentage: 9.5
  
  on:
    rules:
      same_country: HST
    taxes:
      HST:
        versions:
          - starts: 2011-01-01
            ends: 2012-12-31
            percentage: 5